=== johnjohndoe/Kalypso/trunk/KalypsoCore/etc/schemas/model/calcwizard.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="xml.model.kalypso.org" elementFormDefault="qualified" attributeFormDefault="unqualified"
    xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="xml.model.kalypso.org">
    <xs:element name="calcwizard">
        <xs:complexType>
            <xs:sequence minOccurs="1" maxOccurs="unbounded">
                <xs:element name="page">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:sequence minOccurs="0" maxOccurs="unbounded">
                                <xs:element name="arg">
                                    <xs:complexType>
                                        <xs:attribute name="name" type="xs:string" use="required"/>
                                        <xs:attribute name="value" type="xs:string" use="required"/>
                                    </xs:complexType>
                                </xs:element>
                            </xs:sequence>
                        </xs:sequence>
                        <xs:attribute name="className" type="xs:string" use="required"/>
                        <xs:attribute name="pageTitle" type="xs:string" use="required"/>
                        <xs:attribute name="imageLocation" type="xs:string" use="optional"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== johnjohndoe/Kalypso/_import/trunk/KalypsoSachsen/Data/KalypsoSpree/.modellTyp/calcWizard.xml
<?xml version="1.0" encoding="UTF-8"?>
<calcwizard xmlns="xml.model.kalypso.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="xml.model.kalypso.org calcwizard.xsd">

    <page className="org.kalypso.ui.calcwizard.ObservationMapTableDiagWizardPage" pageTitle="Eingabe Niederschlag" imageLocation="icons/calcwizard/boden.gif" >
        <arg name="mapTemplate" value=".modellTyp/vorlagen/rechenfall/ezg.gmt"/>
        <arg name="tableTemplate" value=".modellTyp/vorlagen/rechenfall/table1.ott"/>
        <arg name="diagTemplate" value=".modellTyp/vorlagen/rechenfall/niederschlag.odt"/>

        <arg name="mainSash" value="50"/>
        <arg name="rightSash" value="50"/>
        <arg name="selectionID" value="1"/>
        
        <arg name="timeserie1" value="diagDateAxis=d#diagValueAxis=n#nameColumn=Name#linkColumn=Niederschlag_eingabe"/>
    </page>
<!--
    <page className="org.kalypso.ui.calcwizard.ObservationMapTableDiagWizardPage" pageTitle="Eingabe Talsperrenabgaben" imageLocation="icons/calcwizard/boden.gif" >
        <arg name="mapTemplate" value=".modellTyp/vorlagen/rechenfall/talsperren.gmt"/>
        <arg name="tableTemplate" value=".modellTyp/vorlagen/rechenfall/table1.ott"/>
        <arg name="diagTemplate" value=".modellTyp/vorlagen/rechenfall/talsperren.odt"/>

        <arg name="mainSash" value="50"/>
        <arg name="rightSash" value="50"/>
        <arg name="selectionID" value="4"/>
        
        
        <arg name="timeserie3" value="diagDateAxis=d#diagValueAxis=a#nameColumn=Name#linkColumn=Abgabe"/>
    </page>

    <page className="org.kalypso.ui.calcwizard.ObservationMapTableDiagWizardPage" pageTitle="Eingabe Wasserstände" imageLocation="icons/calcwizard/boden.gif" >
        <arg name="mapTemplate" value=".modellTyp/vorlagen/rechenfall/ezg.gmt"/>
        <arg name="tableTemplate" value=".modellTyp/vorlagen/rechenfall/table1.ott"/>
        <arg name="diagTemplate" value=".modellTyp/vorlagen/rechenfall/wsp.odt"/>

        <arg name="mainSash" value="50"/>
        <arg name="rightSash" value="50"/>
        <arg name="selectionID" value="2"/>
        
        <arg name="timeserie2" value="diagDateAxis=d#diagValueAxis=w#nameColumn=Name#linkColumn=Wasserstand_gemessen"/>
    </page>

    <page className="org.kalypso.ui.calcwizard.ObservationMapTableDiagWizardPage" pageTitle="Eingabe Wasserstände" imageLocation="icons/calcwizard/boden.gif" >
        <arg name="mapTemplate" value=".modellTyp/vorlagen/rechenfall/flusslauf.gmt"/>
        <arg name="tableTemplate" value=".modellTyp/vorlagen/rechenfall/table1.ott"/>
        <arg name="diagTemplate" value=".modellTyp/vorlagen/rechenfall/flusslauf.odt"/>

        <arg name="mainSash" value="50"/>
        <arg name="rightSash" value="50"/>
        <arg name="selectionID" value="8"/>
        
        
        <arg name="timeserie1" value="diagDateAxis=d#diagValueAxis=nied#nameColumn=Name#linkColumn=Niederschlag_eingabe"/>
        <arg name="timeserie2" value="diagDateAxis=d#diagValueAxis=wsp#nameColumn=Name#linkColumn=Wasserstand_gemessen"/>
    </page>

    <page className="org.kalypso.ui.calcwizard.ObservationMapTableDiagWizardPage" pageTitle="Eingabe Zuflüsse" imageLocation="icons/calcwizard/boden.gif" >
        <arg name="mapTemplate" value=".modellTyp/vorlagen/rechenfall/zufluss.gmt"/>
        <arg name="tableTemplate" value=".modellTyp/vorlagen/rechenfall/table1.ott"/>
        <arg name="diagTemplate" value=".modellTyp/vorlagen/rechenfall/zufluss.odt"/>

        <arg name="mainSash" value="50"/>
        <arg name="rightSash" value="50"/>
        <arg name="selectionID" value="16"/>
        
        <arg name="timeserie4" value="diagDateAxis=d#diagValueAxis=z#nameColumn=Name#linkColumn=Zugabe"/>
    </page>

    <page className="org.kalypso.ui.calcwizard.MapAndTableWizardPage" pageTitle="Eingabe NA-Modelle" imageLocation="icons/calcwizard/boden.gif" >
        <arg name="mapTemplate" value=".modellTyp/vorlagen/rechenfall/ezg.gmt"/>
        <arg name="tableTemplate" value=".modellTyp/vorlagen/rechenfall/ezg.gtt"/>
        <arg name="diagTemplate" value=".modellTyp/vorlagen/rechenfall/ezg.odt"/>

        <arg name="mainSash" value="40"/>
        <arg name="rightSash" value="30"/>
        <arg name="selectionID" value="32"/>
        
        
        <arg name="timeserie1" value="diagDateAxis=d#diagValueAxis=w#nameColumn=Name#linkColumn=Niederschlag_eingabe"/>
        <arg name="timeserie2" value="diagDateAxis=d#diagValueAxis=w2#nameColumn=Name#linkColumn=Wasserstand_gemessen"/>
        <arg name="timeserie3" value="diagDateAxis=d#diagValueAxis=w2#nameColumn=Name#linkColumn=Wasserstand_gerechnet"/>
    </page>

    <page className="org.kalypso.ui.calcwizard.MapAndTableWizardPage" pageTitle="Eingabe Talsperren" imageLocation="icons/calcwizard/boden.gif" >
        <arg name="mapTemplate" value=".modellTyp/vorlagen/rechenfall/talsperren.gmt"/>
        <arg name="tableTemplate" value=".modellTyp/vorlagen/rechenfall/talsperren.gtt"/>
        <arg name="diagTemplate" value=".modellTyp/vorlagen/rechenfall/talsperren.odt"/>

        <arg name="timeserie1" value="diagDateAxis=d#diagValueAxis=a#nameColumn=Name#linkColumn=Abgabe_eingang"/>

        <arg name="mainSash" value="50"/>
        <arg name="rightSash" value="40"/>
        <arg name="selectionID" value="64"/>
        
    </page>

    <page className="org.kalypso.ui.calcwizard.MapAndTableWizardPage" pageTitle="Eingabe Flusslaufmodelle" imageLocation="icons/calcwizard/boden.gif" >
        <arg name="mapTemplate" value=".modellTyp/vorlagen/rechenfall/flusslauf.gmt"/>
        <arg name="tableTemplate" value=".modellTyp/vorlagen/rechenfall/flusslauf.gtt"/>
        <arg name="diagTemplate" value=".modellTyp/vorlagen/rechenfall/flusslauf.odt"/>

        <arg name="timeserie1" value="diagDateAxis=d#diagValueAxis=w#nameColumn=Name#linkColumn=Wasserstand_gemessen"/>

        <arg name="mainSash" value="50"/>
        <arg name="rightSash" value="40"/>
        <arg name="selectionID" value="128"/>
        
    </page>
-->
	<!-- Ergebniskontrolle NA-Modelle-->
	<page className="org.kalypso.ui.calcwizard.ExportResultsWizardPage"
	   pageTitle="Ergebniskontrolle Pegel"
	   imageLocation="icons/calcwizard/boden.gif" >
	   	<arg name="mapTemplate" value="project:.modellTyp/vorlagen/rechenfall/ergebniskontrollePegel.gmt"/>
	   	<arg name="tableTemplate"  value="project:.modellTyp/vorlagen/rechenfall/ergebniskontrollePegel.gtt"/>
		<arg name="diagTemplate" value=".modellTyp/vorlagen/rechenfall/results.odt"/>
	
		<arg name="timeserie1" value="diagDateAxis=d#diagValueAxis=w#nameColumn=Name#linkColumn=PegelBerechnung"/>
		<arg name="timeserie2" value="diagDateAxis=d#diagValueAxis=n#nameColumn=Name#linkColumn=NiederschlagMessung"/>
	
	   	<arg name="mainSash" value="50"/>
	   	<arg name="rightSash" value="40"/>
	   	<arg name="selectionID" value="256"/>
	</page>


<!--
	<page className="org.kalypso.ui.calcwizard.MapAndTableWizardPage" pageTitle="Bodenfeuchte" imageLocation="icons/calcwizard/boden.gif" >
	   <arg name="mapTemplate" value=".modellTyp/vorlagen/rechenfall/karte1.gmt"/>
	   <arg name="tableTemplate" value=".modellTyp/vorlagen/rechenfall/table1.gtt"/>
	</page>
-->
</calcwizard>
